name: Generate Multiple jobs

on: push

jobs:
  build_job1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y
              
      - name: Execute cowsay CMD
        run: cowsay -f dragon "Run for cover, I am DRAGON..." > dragon.txt

      - name: Sleep for 30 seconds
        run: sleep 30

  test_job2:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 10 seconds
        run: sleep 10

      - name: Test file exists
        run: grep -i "dragon" dragon.txt

  deploy_job3:
    runs-on: ubuntu-latest
    steps:
      - name: Read file
        run: cat dragon.txt

      - name: deploy
        run: echo "Deploying ....."